name: Android build with WhiteSource Scan

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build BrokenCrypto
      run: |
        chmod +x ./src/MobileShepherd/BrokenCrypto/gradlew
        ./src/MobileShepherd/BrokenCrypto/gradlew build
